site_name: Archives of Learning English and Japanese 

theme:
  # language: ja
  name: material
  custom_dir: overrides
  favicon: img/favicon.png
  font:
    text: Noto Sans Japanese
  icon:
    logo: fontawesome/solid/graduation-cap
  features:
    - navigation.tracking
    - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.indexes
    - toc.integrate 
    # - navigation.expand
    - navigation.sections
    - navigation.path
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Dark mode
      primary: teal

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Light mode
      primary: teal


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra:
  generator: false
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/kanotown
  homepage: archive
  analytics: 
    provider: google
    property: G-9GW9DJ2G09

extra_css:
  - css/extra.css

markdown_extensions: 
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - blog:
      # authors: false
      blog_dir: archive
      enabled: true
      authors_file: archive/.authors.yml
      pagination_per_page: 20
      pagination_url_format: "page/{page}"
      post_url_format: "posts/{slug}"
  - search
  - glightbox

definitions:

  - &page_title_with_site_name >-
    {%- if not page.is_homepage -%}
      {{ page.meta.get("title", page.title) }} - {{ config.site_name }}
    {%- else -%}
      {{ page.meta.get("title", page.title) }}
    {%- endif -%}

  - &page_description >-
    {{ page.meta.get("description", config.site_description) or "" }}

nav:
  - Home: 
    - archive/index.md
  - Number list: 
    - archive/number.md
  - Alphabetical list: 
    - archive/name.md
  - Comics:
    - comic.md
    - English: comic-en.md
  - Back to blog: https://blog.kano.ac/

copyright: 　&copy; Archives of Learning English and Japanese